### ISSUE TITLE
How to enable ReduxDevToolsBehavior

### ISSUE THREAD

**Issue by vchirikov** [TimeWarpEngineering/blazor-state#112]
Hi, first of all thanks for sharing your work.
Hi, I want to try ReduxDevTools with blazor-state, but didn't found sample in docs
```cs
services.AddBlazorState(conf => {
    conf.Assemblies = new[]{
        typeof(Startup).Assembly,
    };
    conf.UseReduxDevToolsBehavior = true;
});
```
And  that I see in firefox:
![ReduxDevTools](https://user-images.githubusercontent.com/40987940/55834703-3274a900-5b23-11e9-8644-19a0161590eb.png)

p.s. `a` prefix for args name in public methods is annoing

**Comment by StevenTCramer** [comment]
Sorry for slow response. Redux Dev Tools are enabled by default in both Server side and client side. Previous versions only supported client side.

**Comment by StevenTCramer** [comment]
This is currently working thus I am going to close this issue.  If you have problems again please file another issue.
