### ISSUE TITLE
Is there an example project anywhere?

### ISSUE THREAD

**Issue by richbryant** [TimeWarpEngineering/blazor-state#139]
Serverside or client-side although honestly, both would be nice.

**Comment by StevenTCramer** [comment]
https://github.com/TimeWarpEngineering/timewarp-templates  contains a Hosted Template that utilizes Dynamic Dual Mode so you can easily switch back and forth from client to server.

**Comment by crh225** [comment]
https://github.com/crh225/BlazorStateReduxDemo

I took the counter app and also added a todo feature. hopefully will help anyone in future.
