### ISSUE TITLE
Subscriptions adding up indefinitely

### ISSUE THREAD

**Issue by Damitrix** [TimeWarpEngineering/blazor-state#140]
So this is my first time building a state based app, but I'm pretty sure it shouldn't be like this.

If you start the TimewarpBlazorApp Template and go to the Counter Page, you can click the Button, which is fine. The Count increases as it should.
But if you spam it, every action will add a 2 new Subscribers, increasing the times the whole component is re-rendered with every click.

So when the Counter hits 140, you can really notice the slowdown.

Is there a way, to remove duplicate Subscriptions? Resetting the Store doesn't help either...

**Comment by StevenTCramer** [comment]
What version are you using?  As that was an issue that I believe I had fixed.  By implementing IDispose in 
https://github.com/TimeWarpEngineering/blazor-state/commit/b1c6da6489deab2ca5d3b2d3d453d86752d485c3

**Comment by Damitrix** [comment]
Ah, pobably should've checked nuget for new versions as well, I just expected the template to be on the newest version.
After updating, everything works as expected, sorry for the trouble!

**Comment by StevenTCramer** [comment]
No worries,  I really appreciate the feedback.

You are right the templates are normally updated along with the library.  I am trying to automate all the CI/CD stuff and keep up with Blazor.  New versions of both hopefully on Monday writh Preview 6 features.
