### ISSUE TITLE
Preview 6

### ISSUE THREAD

**Issue by jrobertshawe** [TimeWarpEngineering/blazor-state#141]
Hi there 

thanks for the great library 

Are there any plans to upgrade to support the latest preview?

thanks

Julian

**Comment by StevenTCramer** [comment]
@jrobertshawe  Absolutely.  I am working on it now.  Seems there are few issues with serialization that I am working through.

I am going to make Redux DevTools disabled by default.

Also found a bug in TypeSupport and issued a PR for that today. https://github.com/replaysMike/TypeSupport/pull/21

Expect and update by Monday.

**Comment by StevenTCramer** [comment]
Preview 6 version was out a few days ago.
