### ISSUE TITLE
More flexibility with cloning state

### ISSUE THREAD

**Issue by michaelvolz** [TimeWarpEngineering/blazor-state#148]
**blazor.state 1.0.0-preview6.19307.2-20190710-124031**
**.NET Core 3.0.100-preview6-012264**

I found some time to experiment with the current Blazor preview and blazor.state. I seem to have ironed out most of the glitches but I have one problem, still: 

I need to use `IOrderedEnumerable<KeyValuePair<string, int>>` but AnyClone does not support this format.

Until now, I just implemented `public override object Clone() => new TilesState(this);` but this does not work any longer. 

One solution would be to have the Clone method optional. Use only if overridden.
If you have a better Idea, I am all ears.

Error:
```
AnyClone.TypeException: Unsupported IEnumerable type: OrderedEnumerable`2
   at AnyClone.CloneProvider`1.
```

**Comment by StevenTCramer** [comment]
@michaelvolz do you have a test object we could use. I will file an issue or a PR with AnyClone.  FYI if a clone method exists on the object it will use it instead of AnyClone.  So you can always override.

But AnyClone makes it easier for sure.

**Comment by michaelvolz** [comment]
I often show ordered data in my views and use just the builtin types. Nothing fancy.

 ```csharp
    public partial class SomeState
    {
        public IOrderedEnumerable<KeyValuePair<string, int>> SomeOrderedData { get; private set; }
    }

    public partial class SomeState
    {
        public class SomeHandler : RequestHandler<SomeRequest, SomeState>
        {
            public SomeHandler(IStore store) : base(store) { }

            public SomeState SomeState => Store.GetState<SomeState>();

            public override async Task<SomeState> Handle(SomeRequest req, CancellationToken token) {
                var dataSource  = ...
                SomeState.SomeData = from entry in dataSource orderby entry.Key select entry;
                return SomeState;
            }
        }
    }

```

**Comment by StevenTCramer** [comment]
@michaelvolz I have been able to duplicate the issue.  I have pinged @replaysMike of AnyClone for advice.

But for this particular case, I suggest you change `SomeOrderData` 

```
public IOrderedEnumerable<KeyValuePair<string, int>> SomeOrderedData => SomeData.OrderBy(entry => entry.key);
```

If you have a public repo with an example I would be happy to look for further options.

If you were to write a clone of this manually how would you clone it?

I have fixed the issue with not calling the IClonable version and added a test case for that.

Please let me know your thoughts.

**Comment by replaysMike** [comment]
I'm currently investigating this and will have a fix out today

**Comment by StevenTCramer** [comment]
The CloneStateBehvaior of Blazor-State will utilize your own clone method if implemented and I highly recommend you write a clone test for every State you create.  AnyClone works great in most cases but you can implement your own.

So I am closing this issue.  Please feel free to reach out on here or connect with me on Discord.
