### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by wrathofodin** [TimeWarpEngineering/blazor-state#160]
Documentation is currently very miserable.

It should describe how to use the library in more detail:

- How to mutate/set/modify state
- How to access the state from blazor components

Basic and minimal TODO example should be included in the docs for easier adoption.

**Comment by StevenTCramer** [comment]
@wrathofodin did you review the "miserable" tutorial?
https://timewarpengineering.github.io/blazor-state/Sample.html

**Comment by wrathofodin** [comment]
Perhaps it's the design of the docs and I didn't notice it. Thanks.

**Comment by StevenTCramer** [comment]
No worries and in case some else gets here.  Feel free to add me on Discord (StevenTCramer#9010) if I don't respond on GH in a timely manner.

![image](https://user-images.githubusercontent.com/357219/62686204-6e931a00-b9ee-11e9-87dc-97f48659fb0d.png)

**Comment by Herdubreid** [comment]
Not sure how you can make this more obvious -- and pretty good tutorial as well.
Got me up and running without any issue.

**Comment by wrathofodin** [comment]
Maybe by using notes like this

![image](https://user-images.githubusercontent.com/3116731/62687367-f6652e00-b9c6-11e9-9d30-aceb71214830.png)

or making it bolder and moving it more up

![image](https://user-images.githubusercontent.com/3116731/62687431-0f6ddf00-b9c7-11e9-9233-ace1cace2101.png)

The first thing that catches my eye is red color - `blazorhosted`

**Comment by StevenTCramer** [comment]
Yep I think I will just add another heading.  You are not the only one that didn't see it.

### Tutorial

**Comment by StevenTCramer** [comment]
I really think using the template is the best way to appreciate the library.

```
dotnet new --install TimeWarp.AspNetCore.Blazor.Templates::1.0.0-3.0.0-preview7.19365.7-*
dotnet new timewarp-blazor -n MyBlazorApp
cd .\MyBlazorApp\
.\run.ps1
```
![image](https://user-images.githubusercontent.com/357219/62688128-78b71780-b9f2-11e9-99d5-c1915f4f474e.png)
