### ISSUE TITLE
Failing to construct services

### ISSUE THREAD

**Issue by Weezeal** [TimeWarpEngineering/blazor-state#168]
I've been following the tutorial available [here](https://timewarpengineering.github.io/blazor-state/Sample.html). However, after completing the **Displaying state in the user interface** stage, I attempt to run the app and receive the following two errors:

`InvalidOperationException: Error while validating the service descriptor 'ServiceType: BlazorState.Features.JavaScriptInterop.JsonRequestHandler Lifetime: Scoped ImplementationType: BlazorState.Features.JavaScriptInterop.JsonRequestHandler': Unable to resolve service for type 'System.Text.Json.JsonSerializerOptions' while attempting to activate 'BlazorState.Features.JavaScriptInterop.JsonRequestHandler'.`

`InvalidOperationException: Unable to resolve service for type 'System.Text.Json.JsonSerializerOptions' while attempting to activate 'BlazorState.Features.JavaScriptInterop.JsonRequestHandler'.`

I copy of my source can be found [here ](https://github.com/Weezeal/BlazorStateTest).

Currently running on preview 8 build 28405-07

**Comment by StevenTCramer** [comment]
Thank's @Weezeal, I will look into this first thing in the morning.  I just updated Blazor-State today.  I will revisit the tutorial and make any required changes.  Thanks much for taking the time to report this.  I am working at a client's at the moment, but will get to this ASAP. I pulled your repo and can duplicate the error.

**Comment by georgemathieson** [comment]
Looks like your not injecting any `JsonSerializerOptions`

**Comment by StevenTCramer** [comment]
@Weezeal @georgemathieson 
New release out that eliminates the need to register JsonSerializerOptions.
Tutorial updated to go with latest release.
I recommend the Timewarp-Blazor Template as the best way to get started with a new project.

Thanks much for reporting this issue.  I welcome your feedback.

https://timewarpengineering.github.io/blazor-state/TemplateOverview.html
