### ISSUE TITLE
 preview 9:  Runtime error adding BlazorState services in startup.cs

### ISSUE THREAD

**Issue by jrobertshawe** [TimeWarpEngineering/blazor-state#178]
blazor.webassembly.js:1 Uncaught (in promise) Error: System.BadImageFormatException: Could not resolve field token 0x04000113, due to: Could not load type of field 'IN4SAdminClient.Startup+<>c:<>9__0_0' (1) due to: Could not resolve type with token 01000024 from typeref (expected class 'BlazorState.BlazorStateOptions' in assembly 'BlazorState, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:BlazorState, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:BlazorState.BlazorStateOptions member:(null) assembly:IN4SAdminClient.dll type:<>c member:(null)

**Comment by StevenTCramer** [comment]
@jrobertshawe Good morning.  I see you closed this issue.  Were you able to resolve the problem?

**Comment by jrobertshawe** [comment]
Yes

Sorry about that - I deleted the Nuget Package and added again - resolved the issue :)

**Comment by StevenTCramer** [comment]
No worries,  Thanks much for checking things out.  Updated template coming today :)
I fogot to bump the sdk version so there is new nuget out that makes it more clear now also.

Docs and tutorial update to p9 in the works too:)

If you have any questions or feedback feel free to ping me.  Thanks.
