### ISSUE TITLE
Guidance for singleton services

### ISSUE THREAD

**Issue by cveld** [TimeWarpEngineering/blazor-state#181]
What would be your guidance for singleton services? 

I tried to implement a simple handler that takes a depency on the singleton service instead of the scoped store. 
Unfortunately the subscriptions are scoped as well.

**Comment by StevenTCramer** [comment]
@cveld Singleton vs Scoped.  Singleton on the server-side would be Global for all clients.  So if State were a Singleton then it would be shared amongst all users.

If subscriptions were a singleton they wouldn't make sense.  Telling client A StateHasChanged on a component that was rendered on Client B wouldn't make sense.

But your handlers can take a dependency on a Singleton.  Let me know a bit more about what you are trying to do and I can try and help.

**Comment by cveld** [comment]
Hi Steven, I am trying to setup a multi-node multi-client real-time webapp.
Imagine a vacation planner with ratings. If one user has multiple tabs open
and a second user as well, the updated rating would need to be reflected in
all tabs across horizontally scaled nodes. I have set up a SingleR hub on
the backend to transmit all events across the nodes. I have created a
handler that updates a singleton state. This singleton currently contains
its own subscriptions which are registered by the Blazor components. The
components have to call their StateHasChanged currently explicitly
themselves. This is not a scalable / practical setup. I am figuring I would
need a thin singleton subscription manager and reactive components with
scoped state (or some dbset virtual shared singleton state for memory
optimization purposes). When the scoped state gets disposed the attached
subscriptions would need to be removed as well.

Op ma 16 sep. 2019 om 20:36 schreef Steven T. Cramer <
notifications@github.com>:

**Comment by StevenTCramer** [comment]
interesting.  Let me see if I understand.

ClientA has some StateX,  ClientB also has the same StateX .  You want ClientB to be updated when ClientA changes StateX?

Your components that display the StateX would be subscribed to that local state.  So if your SignalR Hub is sending Actions to the client   `UpdateStateX` for example then when the handler processes the Action the components would update.

But I don't think I am understanding your goal.

Please add me to Discord and lets chat.  StevenTCramer#9010

**Comment by StevenTCramer** [comment]
We discussed on Discord some time ago.  So am going to close this.  Thanks.
