### ISSUE TITLE
State Initialize called twice

### ISSUE THREAD

**Issue by Herdubreid** [TimeWarpEngineering/blazor-state#197]
It looks like the State is Initialized twice when a BlazorStateComponent is the opening page.

Steps to test with with the Blazor Counter example:

1. Put a break-point on the Initialize method of the CounterState class.
2. Run the app and select the Counter page.  The app will break once on the Initialize method.
3. Refresh the page (stay on the Counter page).
4. The app will break twice on the Initialize method.

My workaround is a __Loaded__ logic on the MainLayout.razor component:
```csharp
    bool Loaded { get; set; }
    protected override void OnAfterRender(bool firstRender)
    {
        if (firstRender)
        {
            Loaded = true;
            StateHasChanged();
        }
        base.OnAfterRender(firstRender);
    }
```
No BlazorStateComponents are loaded until the Loaded flag is true.

**Comment by StevenTCramer** [comment]
Hmm what version are you using?

**Comment by Herdubreid** [comment]
I created a new project to test this (it has some DevExpress refrerences that are commented out) :
https://github.com/Herdubreid/TestBlazorState.git

**Comment by StevenTCramer** [comment]
Thanks, will take a look in a few hours at dinner.

**Comment by StevenTCramer** [comment]
@Herdubreid I can duplicate the issue. On your repo (server side) but not in my test app (hosted).
Looking for Root cause ;)
Thanks for reporting this.  Scratching head! :)

**Comment by StevenTCramer** [comment]
It is because of the prerender. When loading the page it effectively loads it twice.  This is by design.
see https://github.com/aspnet/AspNetCore/issues/14903

Thx @mrpmorris for point this out to me.

So what problem is this causing you?  Maybe we can use your problem to get that issue reconsidered by the team?

**Comment by Herdubreid** [comment]
Ahh, great thanks!  I thought I was missing something so this was doing my head in.

My app updates the state with Azura data on initialize, [see example](https://github.com/Herdubreid/DataBrowser/blob/master/Pages/QueryRequestList.razor).

This caused the page to 'flicker', because it initialized twice ([double render glitch](https://github.com/aspnet/AspNetCore/issues/14903#issuecomment-542533583)).

My workaround is to wait for the first render on the [MainLayout page](https://github.com/Herdubreid/DataBrowser/blob/master/Shared/MainLayout.razor).

I've noticed similar 'flickering' on a demo page from [DevExpress](https://demos.devexpress.com/blazor/GridColumnTypes), which I'm guessing is caused by this behavior.

I think this needs to be addressed by the team and at least documented with recommended workarounds.

**Comment by mrpmorris** [comment]
If you don't need prerendering you can change it in /Pages/_Host.cshtml

Replace ServerPrerendered with Server

**Comment by Herdubreid** [comment]
The downside of replacing ServerPrerender with Server is the blank page until it's rendered -- this might only be milliseconds but enough to strike you with the thought of  _something's wrong_ .

My workaround shows the loading icon, which could be expanded to a splash page.
