### ISSUE TITLE
UI will not update after individual actions

### ISSUE THREAD

**Issue by chiefch33se** [TimeWarpEngineering/blazor-state#198]
I'm dispatching two actions under one method. The state will change (Message1 first then 1 second later Message2) but the UI will only update after the method that calls the two message update actions finishes.

I've replicate this issue in [this repo](https://github.com/chiefch33se/blazor-tour-of-heroes). I found this issue while at work trying to implement a loading screen.

To see this navigate to "/State" and click the button. The first false should turn true instantly and the second should turn true after one second.

The page is called "State" and the message handlers and actions are under Common/State/Details

**Comment by StevenTCramer** [comment]
Thanks @chiefch33se for the issue I will take a look on the weekend.  Hopefully this is ok.  Thanks.

**Comment by nstohler** [comment]
@chiefch33se I've cloned your repo and played around with it (since I wanted to take a look at a somewhat more complex example that uses blazor-state). With the following changes, the "/State" page works.

Though I cannot really explain why. I only switched the methods to be async and replace Thread.Sleep(...) with await Task.Delay(...).

**HandleMessage1:**
```
public override async Task<Unit> Handle(DetailsState.Message1Action aAction, CancellationToken aCancellationToken)
            {
                await Task.Delay(200, aCancellationToken).ConfigureAwait(true);
                DetailsState.Message1 = true;

                return Unit.Value;
            }
```

**HandleMessage2:**
```
public override async Task<Unit> Handle(DetailsState.Message2Action aAction, CancellationToken aCancellationToken)
            {
                await Task.Delay(1000, aCancellationToken).ConfigureAwait(true);
                DetailsState.Message2 = true;

                return Unit.Value;
            }
```

**Comment by chiefch33se** [comment]
@nstohler that does solve it thanks! Something to note as well is if you are calling a service, that service method will need to be async AND have an await.
