### ISSUE TITLE
Making the Weather Forecast Service call an actual API instead of returning mock data does not work

### ISSUE THREAD

**Issue by gices** [TimeWarpEngineering/blazor-state#199]
I was having a play around with your timewarp-blazor template and I noticed an issue if you were to make the weather forecast service call an actual API instead of returning mock data.

In .\MyTimeWarpBlazorApp\Source\Server\Features\WeatherForecast\GetList\GetWeatherForecastsHandler.cs if you were to inject HttpClient, the noticeable error you'd see is "Error constructing handler for request of type MediatR.IRequestHandler" but in the InnerException you'd see the actual problem is "RemoteNavigationManager' has not been initialized".

To reproduce the error, you can just add a constructor in the above mentioned file with HttpClient as parameter to be injected.

I've done it in the below way following [a thread about this problem](https://github.com/aspnet/AspNetCore/issues/11867):

    private readonly IServiceProvider _provider;

    public GetWeatherForecastsHandler(IServiceProvider provider)
    {
      _provider = provider;
    }

    public async Task<GetWeatherForecastsResponse> Handle
    (
      GetWeatherForecastsRequest aGetWeatherForecastsRequest,
      CancellationToken aCancellationToken
    )
    {
      HttpClient client = _provider.GetRequiredService<HttpClient>();
    }

This is not a problem with Blazor-State itself (as I understand) but I'd like to see how differently you'd structure the api calls to get this working.

Thanking you in anticipation.

**Comment by StevenTCramer** [comment]
@gices Sorry for slow response, just started a new job.  I will try and take a look this weekend.  Thanks for the link.

**Comment by gices** [comment]
@StevenTCramer thanks for getting back to me.

I fixed it day after I opened this issue here; had to request HttpClient from HttpClientFactory to make it work.

Very slick package you've developed I must say!

Hope your new job is going well :)
