### ISSUE TITLE
Add Overridable Method on BlazorStateComponent That Will Be Invoked on Dispose

### ISSUE THREAD

**Issue by AbeBaehaki** [TimeWarpEngineering/blazor-state#200]
I think it will be a nice addition to be able to execute something when the component is disposed. Something like this maybe in `BlazorStateComponent.cs`. What do you think?

```
    protected virtual void OnDispose() { }
    public void Dispose()
    {
      Subscriptions.Remove(this);
      OnDispose();
    }
```

**Comment by StevenTCramer** [comment]
Thanks for using blazor-state and take the time to give your input.
I will be updating to 3.1 this weekend. So if this is something we determine beneficial it could make it in. 

Can you give me an example use case?
I am thinking you probably have your own base component in your code that you could implement Dispose on?

The BlazorStateComponent is ensuring it clears the stuff it responsible for.

**Comment by AbeBaehaki** [comment]
In my case, I needed to update a state when a component is disposed. My first attempts is to hide the BlazorStateComponent Dispose method in my component, but that did not work. 

Then I figure I can create my own base component, but seems like I would need to manage the component state change manually? Since if I were to create a GetState<T> method, the `Subscriptions.Add` only accept component of type `BlazorStateComponent `.

```
    protected T GetState<T>()
    {
      Type stateType = typeof(T);
      Subscriptions.Add(stateType, this);
      return Store.GetState<T>();
    }
```

I guess changing `Subscriptions.Add` method to accept `IBlazorStateComponent` interface instead can be an option. Or maybe my assumption of how the component state changes are handled is wrong?

Also, thank you for creating such an awesome library. 👍

**Comment by StevenTCramer** [comment]
Have your base component inherit from BlazorStateComponent.  Then you can dispose your stuff and it will manage the subscritpions.

**Comment by AbeBaehaki** [comment]
Aha! I see. So seems like I missed a small but important detail here.

```cs
    public class MyComponentBase1 : BlazorStateComponent
    {
        public new void Dispose()
        {
            throw new Exception("WILL NOT BE CALLED");
            base.Dispose();
        }
    }

    public class MyComponentBase2 : BlazorStateComponent, IDisposable
    {
        public new void Dispose()
        {
            throw new Exception("WILL BE CALLED");
            base.Dispose();
        }
    }
```

Previously, I wrote my base component like the `MyComponentBase1` in the snippet and the dispose does not work as expected. After I changed it like the `MyComponentBase2`, then It works. 

Thank you! I will now close this issue.
