### ISSUE TITLE
Docs WAY out of date

### ISSUE THREAD

**Issue by richbryant** [TimeWarpEngineering/blazor-state#203]
Try following the instructions on https://timewarpengineering.github.io/blazor-state/Sample.html verbatim.

Your first compile error will come with GetState<T> which appears not to exist.  The second comes in implementing partials.

Basically, nothing works.  I've just tried it twice.

**Comment by StevenTCramer** [comment]
Rich,

The link you have is an old one and by the nature of how docfx site is generated it isn't deleted.  I am curious how you you got there. Maybe you saved that link from earlier?

I explicitly deleted the whole doc site and regenerated it.

Anyway https://timewarpengineering.github.io/blazor-state/Tutorial.html  Should be what you want.

Thanks for checking it out.  If you have any other issues please reach out.  If this solves your problem please close this issue.  Thanks.

**Comment by richbryant** [comment]
actually, it was the first hit from Google

**Comment by StevenTCramer** [comment]
@richbryant Hopefully new docs helped you out.  If not please feel free to repopen or ping me on discord.

**Comment by richbryant** [comment]
new docs are great, thank you
