### ISSUE TITLE
FYI: Nuget REST API

### ISSUE THREAD

**Issue by Herdubreid** [TimeWarpEngineering/blazor-state#205]
For some reason the Nuget REST API doesn't return details about your package:
``
https://azuresearch-usnc.nuget.org/query?q=packageid:Blazor-State
``
I've sent a support email to Nuget about this, but thought I'll notify you as well.

**Comment by Herdubreid** [comment]
Got a reply:
All the listed versions of the Blazor-State package have SemVer 2 versions. To be able to get SemVer 2 results in the search service output, please make sure you specify &semVerLevel=2.0.0 parameter in the search URL:
``
https://azuresearch-usnc.nuget.org/query?q=packageid:blazor-state&semVerLevel=2.0.0
``

**Comment by StevenTCramer** [comment]
Ah good to know. Thanks :)
