### ISSUE TITLE
state in a layout.

### ISSUE THREAD

**Issue by dionysus55** [TimeWarpEngineering/blazor-state#206]
Can I just inject the needed state into a blazor layout?

**Comment by StevenTCramer** [comment]
A Layout only needs to implement IComponent and have a Body parameter. 

If you look at the test app.

https://github.com/TimeWarpEngineering/blazor-state/blob/master/Tests/TestApp/Client/Layout/MainLayout.razor.cs

And change that too:

```
  public class MainLayoutBase : BaseComponent
  {
    [Inject] public BlazorHostingLocation BlazorHostingLocation { get; set; }

    [Parameter] public RenderFragment Body { get; set; }
  }
```
then your layout has access to whatever State you expose via BaseComponent.

Please let me know if this solves your issue.  

Thanks.
