### ISSUE TITLE
Blazorstate.js only included as static files in _content when asp.net core environment is Development

### ISSUE THREAD

**Issue by ArneVanBael** [TimeWarpEngineering/blazor-state#211]
Hey, 

I am trying to implement the Blazor-state library in an new project i am working on. I also managed to get the redux dev tools working with the ASPNETCORE_ENVIRONMENT "Development" in my launchSettings.json.

But I also have a environment called "Test" where I want the redux dev tools to be enabled. But the moment I change the ASPNETCORE_ENVIRONMENT to "Test" the blazor-state.js is not published to the _content folder anymore?

This is the situation in environment "Development"
![image](https://user-images.githubusercontent.com/32770704/79971481-a8308600-8494-11ea-8144-97d776c839da.png)

And this is the situation in environment "Test"
![image](https://user-images.githubusercontent.com/32770704/79971644-e037c900-8494-11ea-9a14-afdca6ee1afa.png)

**Comment by StevenTCramer** [comment]
My apologies, I just saw this, I have been busy. Will take a look this weekend, I am do for upgrade as official release is soon

**Comment by StevenTCramer** [comment]
The issue I think you are having is addressed in the docs. https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.1&tabs=visual-studio#consume-content-from-a-referenced-rcl

In your Server Startup make sure you have 

```
  app.UseStaticFiles();
```
And in your Program.cs

```
webBuilder.UseStaticWebAssets();
```

I have updated the timewarp-template  to include this also.
