### ISSUE TITLE
Slow when storing array of data from API call

### ISSUE THREAD

**Issue by jrobertshawe** [TimeWarpEngineering/blazor-state#216]
Hi 

I have tired many things to improve the performance but I am worried I am doing it very wrong.   It appears that maybe memory is being recovered between calls as the first call return in about 400ms but after that it takes about 4000ms. 

State object member is an array 
        public INQ_ID4U_ENT_DTO[] MeItems { get; private set; }
I get the data from the server like this 
 INQ_ID4U_ENT_DTO[] MeItems = await _httpClient.GetJsonAsync<INQ_ID4U_ENT_DTO[]>($"id4u_ent/inq_id4u_ent", "in4m_now");
  
Only when I set the state variable to the array returned from the HTTP call does it become very slow. 
I am seeing these messages in the console at each call.
L: GC_MAJOR_SWEEP: major size: 2784K in use: 28752K
blazor.webassembly.js:1 L: GC_MAJOR: (LOS overflow) time 8.89ms, stw 8.90ms los size: 1024K in use: 8K
             

Should I not use the blazer state to receive and cache datasets?

thanks you 

Julian

**Comment by StevenTCramer** [comment]
@jrobertshawe is this in production mode or just in Debug mode?  

If ReduxDevtools are enabled this very well could be the issue.  Disable them and see if this helps.

`aOptions.UseReduxDevToolsBehavior = false;`

https://timewarpengineering.github.io/blazor-state/Topics/AddReduxDevTools.html

**Comment by StevenTCramer** [comment]
ReduxDevTools are not memory efficient.  Great help for debugging but do NOT leave them on in production.
