### ISSUE TITLE
State per object instance

### ISSUE THREAD

**Issue by babinecm** [TimeWarpEngineering/blazor-state#217]
Hi,
I have the one page with many tabs. Every tab has it's own instance of an object (Simulation 1, Simulation 2, ...), so every object has independent data.
If I create SimulationState class and then I change data on Simulation 1 Tab, state will be changed and data will be updated on all other tabs too.
So, it is possible to have a state per object instance? Any ideas?
Thank you.

**Comment by ITninja04** [comment]
Just a thought, but tried to store the tabs as a dictionary or some other key value store? 

[Observable Dictionary](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identityserver.management.resources.observabledictionary-2?view=adfs-2019)

**Comment by StevenTCramer** [comment]
@babinecm My first thought is the same as @ITninja04 have your SimulationState use some kind of Collection.

Let me know how this works or doesn't work :)

**Comment by babinecm** [comment]
I created a simple dictionary property in my SimulationState class:

`public IDictionary<long, SimulationDto> Simulations { get; private set; }`

On a page I loaded the SimulationState and on the current tab I accessed the Simulation object like this

`var tabSimulation = SimulationState.Simulations[id];`

After data change on the specified Simulation only one tab with this Simulation was updated. Other tabs remained unchanged.

It seems that it works :-)

**Comment by StevenTCramer** [comment]
Excellent!
