### ISSUE TITLE
Save state over authentication redirects

### ISSUE THREAD

**Issue by brettwinters** [TimeWarpEngineering/blazor-state#218]
Hi @StevenTCramer 

I've just started testing your library - great effort! appreciate your work! 

Have you considered saving the user's state into session so that it's not lost due to authentication redirects when their token expires? 

The ASP.net team has some instructions [here](https://docs.microsoft.com/en-us/aspnet/core/security/blazor/webassembly/additional-scenarios?view=aspnetcore-3.1#save-app-state-before-an-authentication-operation). 

I guess you're already serializing/deserializing for the redux tools / time travel and you already have an id/guid for each state instance so its just a matter of saving/retrieving from session in a custom Authentication.razor... I think I could do it, but it would take me 100x longer than you! 

Regards

Brett

**Comment by StevenTCramer** [comment]
@brettwinters Excellent idea. 
I have plans (just not time) to allow the option to persist in local storage.  
So adding this option would be good also.

- [ ] Devise plan to persist state.

100x longer... (Don't count on it) I'm not fast just persistent (ironic) :)

**Comment by StevenTCramer** [comment]
@brettwinters I now do this using middleware and it works quite well.
I use Sainty's Blazored.LocalStorage and a PostProcessor and make sure I can serialize the state. See a snippet of in production code.

```
  public class PersistUserMessageStatePostProcessor<TRequest, TResponse> : IRequestPostProcessor<TRequest, TResponse>
  {
    private readonly ILocalStorageService LocalStorageService;
    private readonly IStore Store;

    public PersistUserMessageStatePostProcessor
    (
      IStore aStore,
      ILocalStorageService aLocalStorageService
    )
    {
      Store = aStore;
      LocalStorageService = aLocalStorageService;
    }

    public async Task Process(TRequest aRequest, TResponse aResponse, CancellationToken aCancellationToken)
    {
      Type requestType = typeof(TRequest);
      Type declaringType = typeof(TRequest).DeclaringType;
      if (typeof(UserMessageState).IsAssignableFrom(declaringType))
      {
        var userMessageState = Store.GetState(declaringType) as UserMessageState;
        var serializableUserMessageState = new SerializableUserMessageState(userMessageState);

        await LocalStorageService
          .SetItemAsync(nameof(UserMessageState), JsonSerializer.Serialize(serializableUserMessageState))
          .ConfigureAwait(false);
      }
    }
  }
  ```
