### ISSUE TITLE
The JSON value could not be converted to System.Int32.

### ISSUE THREAD

**Issue by Jayson-Furr** [TimeWarpEngineering/blazor-state#227]
When using Redux DevTools, after following the tutorial, if I attempt to "Jump" to a point in time I get a WASM error of the following:

`System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.id | LineNumber: 0 | BytePositionInLine: 376. ---> System.InvalidOperationException: Cannot get the value of a token type 'String' as a number.`

Looking into it a bit it seems the id from states are serialized as strings, while Newtonsoft handled this well, System.Text.Json does not. Have you come across this before?

![image](https://user-images.githubusercontent.com/53241637/91588697-34a8f480-e91e-11ea-8c7e-53e069849691.png)

**Comment by StevenTCramer** [comment]
Time travel is not supported.  Supporting it is quite a bit of trouble and I personally don't use it.  If you want to take the time to do a PR that would be great but I don't intend to implement it.  Sorry.
