### ISSUE TITLE
Will Blazor-state support generics in the State?

### ISSUE THREAD

**Issue by WayneHiller** [TimeWarpEngineering/blazor-state#228]
Will Blazor-state support generics in the State something like this?

```
public partial class SomeState<T> : State<SomeState<T>>
  {
    public IEnumerable<T> List { get; private set; }
  }
```

I was using Fluxor until I found out it would not support Generic types.

**Comment by mikeyoshino** [comment]
Hi, I have spent few hours testing the given scenario and it seems Blazor state does not support the generics in the state. We try to come up with solutions and from what we discussed it would not be a good idea for having generics in the state. 

Could you be able to give us concrete examples of what you would like to do with generic and what could be beneficial for it.
We will look at it again base on your example and see if we can make improvements to Blazor state.

**Comment by WayneHiller** [comment]
There are quite a few list type components that use Generics for the items. I am using a Telerik Grid that also uses a Generic in it's State object (Column position, Order etc). Generics are quite common in C#. I ending up just creating my own State objects, I don't need them so much for sharing data as I do for persistence.

**Comment by StevenTCramer** [comment]
@WayneHiller I would love to see an example of what you are doing.  Feel free to add me on discord and maybe on a weekend you can show me.  StevenTCramer#9010
