### ISSUE TITLE
Updating other components after CounterState change

### ISSUE THREAD

**Issue by FolkertVreeken** [TimeWarpEngineering/blazor-state#230]
Hi,

I played a bit with the code in the tutorial (https://timewarpengineering.github.io/blazor-state/Tutorial.html).
After that, I injected a IStore inside the NavMenu template.

In the code, I wrote the following: int Count => Store.GetState<CounterState>().Count;
Based on that, I am able to present the count value behind the Counter link in het NavMenu:
<NavLink class="nav-link" href="counter">
     <span class="oi oi-plus" aria-hidden="true"></span> Counter (@Count)
</NavLink>

It initializes correctly when the application starts up.
Although the value is not updated on each click on the button on the Counter page but only after routing to another page.

How can I implement live updates on the NavMenu after every change in CounterState?

Thank you for your reply and help!

Regards,

Folkert

**Comment by FolkertVreeken** [comment]
See for example the approach in Fluxor (https://www.youtube.com/watch?v=k_c-ErPaYa8&t=963s, starting at 15:33).

**Comment by StevenTCramer** [comment]
@FolkertVreeken Thanks for trying out Blazor-State.

Very much like Fluxor if the component inherits from `BlazorStateComponent` it will auto update.

I will make a video example for you this weekend.

**Comment by FolkertVreeken** [comment]
Thanks Steven,

I got it. NavMenu should not use / inject IStore but inherit from BlazorStateComponent.
You than can indeed simply call GetState<CounterState>. Auto update is there.

Many thanks,
Folkert

**Comment by StevenTCramer** [comment]
@FolkertVreeken Awesome. Glad to hear.
