### ISSUE TITLE
Latest version 3.3.0 creates ILLinker error

### ISSUE THREAD

**Issue by Kronos11** [TimeWarpEngineering/blazor-state#233]
`Fatal error in Mono IL Linker
build	04-Nov-2020 18:57:16	/home/bamboo/.nuget/packages/microsoft.aspnetcore.components.webassembly.build/3.2.1/targets/Blazor.MonoRuntime.targets(326,5): error : Unhandled exception. Mono.Linker.MarkException: Error processing method: 'System.Void SmartWorkflow.Application.Processors.SaveWorkItemProcessor/<Run>d__6::MoveNext()' in assembly: 'SmartWorkflow.Application.dll' [/home/bamboo/bamboo-agent-home/xml-data/build-dir/PHOENIX-SWM1-TESTANDPUBLISH/src/Marvin/Client/Marvin.Client.csproj]
build	04-Nov-2020 18:57:16	   ---> Mono.Cecil.ResolutionException: Failed to resolve System.Threading.Tasks.Task`1<!!0> MediatR.IMediator::Send(MediatR.IRequest`1<!!0>,System.Threading.CancellationToken)
build	04-Nov-2020 18:57:16	     at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
build	04-Nov-2020 18:57:16	     at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
build	04-Nov-2020 18:57:16	     at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
build	04-Nov-2020 18:57:16	     at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
build	04-Nov-2020 18:57:16	     at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
build	04-Nov-2020 18:57:16	     at Mono.Linker.Steps.MarkStep.ProcessQueue()
build	04-Nov-2020 18:57:16	     --- End of inner exception stack trace ---
build	04-Nov-2020 18:57:16	     at Mono.Linker.Steps.MarkStep.ProcessQueue()
build	04-Nov-2020 18:57:16	     at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
build	04-Nov-2020 18:57:16	     at Mono.Linker.Steps.MarkStep.Process()
build	04-Nov-2020 18:57:16	     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
build	04-Nov-2020 18:57:16	     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
build	04-Nov-2020 18:57:16	     at Mono.Linker.Pipeline.Process(LinkContext context)
build	04-Nov-2020 18:57:16	     at Mono.Linker.Driver.Run(ILogger customLogger)
build	04-Nov-2020 18:57:16	     at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
build	04-Nov-2020 18:57:16	     at Mono.Linker.Driver.Main(String[] args)
build	04-Nov-2020 18:57:16	/home/bamboo/.nuget/packages/microsoft.aspnetcore.components.webassembly.build/3.2.1/targets/Blazor.MonoRuntime.targets(326,5): error : ILLink failed with exit code 134. [src/Marvin/Client/Marvin.Client.csproj]`

The reference up there SmartWorkflow.Application uses the same Mediatr version as this project.

as soon as I reverted back to 3.2.4 it worked fine again.

**Comment by ShadyNagy** [comment]
You need to be sure all your projects use the same versions as you can see changes on
- MediatR
- MediatR.Extensions.Microsoft.DependencyInjection
- Microsoft.AspNetCore.Components.Web
- Microsoft.Extensions.Logging.Abstractions

If that does not help then better you upload a sample code of the problem so we can deep inside it.

Dependencies 3.3.0
```
    AnyClone (>= 1.0.39)
    MediatR (>= 9.0.0)
    MediatR.Extensions.Microsoft.DependencyInjection (>= 9.0.0)
    Microsoft.AspNetCore.Components.Web (>= 3.1.9)
    Microsoft.Extensions.Logging.Abstractions (>= 3.1.9)
    TypeSupport (>= 1.1.4)
```
Dependencies 3.2.4
```
    AnyClone (>= 1.0.39)
    MediatR (>= 8.1.0)
    MediatR.Extensions.Microsoft.DependencyInjection (>= 8.1.0)
    Microsoft.AspNetCore.Components.Web (>= 3.1.6)
    Microsoft.Extensions.Logging.Abstractions (>= 3.1.6)
    TypeSupport (>= 1.1.4)
```
