### ISSUE TITLE
BlazorHostingLocation HasMono not working under net5.0

### ISSUE THREAD

**Issue by FolkertVreeken** [TimeWarpEngineering/blazor-state#235]
Apparently checking for Mono.Runtime is not useful anymore to check whether the blazor app is hosted serverside or clientside.

public bool HasMono => Type.GetType("Mono.Runtime") != null;

How can we check for running clientside / WASM under net5.0?

**Comment by StevenTCramer** [comment]
@FolkertVreeken  hmm will have to check.  I hope to migrate much of my stuff to dotnet 5 C#9 over XMas - new years.

**Comment by StevenTCramer** [comment]
Should work on dotnet 5 but I have not moved testing etc... to it yet.
