### ISSUE TITLE
State initialize to be async/await?

### ISSUE THREAD

**Issue by ducman** [TimeWarpEngineering/blazor-state#252]
I'm wondering if the below can be changed to return back a `Task`. Only asking because there's a chance that the app has to use the `HttpClient` to make a request which is also async/await to get initial data for the state.

https://github.com/TimeWarpEngineering/blazor-state/blob/49569de6c79f7e2b221e4cf1adcf5cbfd69f8bd6/Source/BlazorState/State/State.cs#L39

**Comment by StevenTCramer** [comment]
@ducman  I guess I could but I don't think fetching data in Initialize is a good idea.  Instead, I recommend you have an action to fetch data and then Send that action in a Lifecycle method of a component that needs the data.  And if the data is needed globally you could Send the Action on the App component.

If I make it async then that would be a breaking change that would bubble up. I have not needed this yet.

Can you think of any other async method you would want other than fetching?
