### ISSUE TITLE
Tutorial?

### ISSUE THREAD

**Issue by KevinBurton** [TimeWarpEngineering/blazor-state#254]
I followed the tutorial under documentation and all seemed to work but I looked at the output of the debugger console in Chrome DEV Tools and I see these messages:

Redux DevTools are not installed.
ReduxDevTools.ts:53 Unable to connect to Redux DevTools.
Initialize.ts:12 InitializeJavaScriptInterop

Should I be concerned? They are not error messages but I don't think I am connected with the Chrome Redux DEV Tools.

**Comment by StevenTCramer** [comment]
The error message is saying that you have ReduxDev Tools Enabled in Blazor State but it is not installed in your browser.

You can install it from:
https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd

Please let me know if you have any more issues. 

Thanks!

**Comment by KevinBurton** [comment]
But Chrome says the tools are installed?

![image](https://user-images.githubusercontent.com/2643566/110357762-4112b600-8001-11eb-937a-6ec2117e95e8.png)

**Comment by StevenTCramer** [comment]
@KevinBurton were you able to get this going.  I have not had anyone else have this problem.  If you still can't get it to work please contact me on discord. https://discord.gg/uHaSywCYY7 And we will try to help. Thanks.
