### ISSUE TITLE
Initialize state from BlazoredLocalStorage

### ISSUE THREAD

**Issue by diskman** [TimeWarpEngineering/blazor-state#258]
Hi,

I am starting now my journey with Blazor. Is there any practice how to initialize the state from local storage?  

```
public partial class UserProfileState : State<UserProfileState>
    {
        public string DisplayName { get; private set; }
        public override void Initialize()
        {
            // here I would like to use local storage to check if I can init state from local storage
            DisplayName = "";
        }
    }
```

**Comment by mikeyoshino** [comment]
Hi, Sorry for the late. Have you got the answer to your question?
if you follow the tutorial on how to use Blazor state, the only way to assign or set the value to the state is to send action that can mutate the state.
 
You may have an action call **IncrementCountAction** 

`namespace Sample.Client.Features.Counter
{
  using BlazorState;

  public partial class CounterState
  {
    public class IncrementCountAction : IAction
    {
      public int Amount { get; set; }
    }
  }
}`

and the handler for that action.
`namespace Sample.Client.Features.Counter
{
  using System.Threading;
  using System.Threading.Tasks;
  using BlazorState;
  using MediatR;

  public partial class CounterState
  {
    public class IncrementCountHandler : ActionHandler<IncrementCountAction>
    {
      private readonly LocalStorageService LocalStorageService;
      public IncrementCountHandler(IStore aStore, LocalStorageService aLocalStorageService) : base(aStore) 
      {
           LocalStorageService = aLocalStorageService;
      }

      CounterState CounterState => Store.GetState<CounterState>();

      public override Task<Unit> Handle(IncrementCountAction aIncrementCountAction, CancellationToken aCancellationToken)
      {
        //Read value from you localstorage here
        CounterState.Count = here you assign the value to the state.
        return Unit.Task;
      }
    }
  }
}`

In your component, you can send the action in your component or in your Initialize method like below.

`public override void Initialize() => await Send(new IncrementCountAction(){ Amount  = value to want to send to handler };`

if you have any question please let me know. :)

**Comment by diskman** [comment]
hi @mikeyoshino 

I was trying to init state in the wrong place. Thanks again .
