### ISSUE TITLE
Dom not updating when setting a DynamicComponent with blazor-state action

### ISSUE THREAD

**Issue by wendellmva** [TimeWarpEngineering/blazor-state#275]
Hi I have a stackoverflow question [here](https://stackoverflow.com/questions/70690217/blazor-client-side-dynamic-component-in-mudblazor-component-not-updating-dom-aft).

I am using mudblazor and blazor-state together it was working great until I ran into a problem where I was using an action to set the type of a DynamicComponent, I expected it to render and show the component which it doesn't. It looks like the dom is not updating, only when I click the link a second time the component shows up, I have uploaded the code [here](https://github.com/wendellmva/blazor-state_with_mudblazor), any help will be much appreciated.e uploaded the code [here](https://github.com/wendellmva/blazor-state_with_mudblazor), any help will be much appreciated.

**Comment by mikeyoshino** [comment]
Hi, I have looked at your code and it seem like you are calling the sidebar which is located in your MainLayout but in your example page you are not using any Layout. 

To fix it you can simply do like this
`<MainLayout>
    <Body>
        <PageTitle>Example</PageTitle>

        <h1>Example</h1>

        <MudPaper Class="pa-2 mt-2">
            <MudText Typo="@Typo.subtitle1">Activated item: @(ActivatedValue?.Title)</MudText>
            <MudText Typo="@Typo.subtitle1">Sum of selected items: @GetSelectedSum()</MudText>
        </MudPaper>
    </Body>
</MainLayout>`

Hope this help :) if you have further question please let me know.

**Comment by wendellmva** [comment]
Thank you so much that worked ...

**Comment by wendellmva** [comment]
I solved it by using this [article](https://tipsfordev.com/blazor-wasm-update-navigation-when-collection-changes). 

``` c#
    #region "SidebarComponent"
    public event Action SidebarComponentChanged;
    private Type _sidebarComponent;
    public Type SidebarComponent
    {
        get => _sidebarComponent;
        set
        {
            _sidebarComponent = value;
            SidebarComponentChanged?.Invoke();
        }
    }
    #endregion
```

I added an event action in the AppState which was being invoked whenever the OpenStartComponent is set. In the MainLayout I added an event listener.

``` c#
    protected override async Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();

        AppState.SidebarComponentChanged += () => InvokeAsync(StateHasChanged);
    }
```

Works like a charm ...
