### ISSUE TITLE
License collision

### ISSUE THREAD

**Issue by astrowalker** [TimeWarpEngineering/blazor-state#279]
It looks (for me) this project cannot use Unlicense license because one of its dependencies (AnyClone) is released under GPL license. So this makes this project GPL as well.

**Comment by StevenTCramer** [comment]
Do you have any references where I can read up on this?  I want the most permissive option there is.  I don't see why a dependency changes my license.  You can fork and remove them as they are not required. If you don't want automatic cloning.

Anyway if you could link to some further information that would be great.

**Comment by astrowalker** [comment]
I am already in process of checking out how technically it can be solved without any doubt -- I noticed AnyClone can be replaced with DeepCloner (MIT license) and TypeSupport (AGPL) can be removed completely from the lib because it is not used. I am not sure how this will affect entire project because I had problems building all the parts (my bad, I am not that advanced :-) ).

I am not a lawyer, but this is a good read: https://en.wikipedia.org/wiki/GPL_linking_exception And I checked the license and I don't see any axception.

But there is another angle to it -- if you want to use the most open license the consumer will be hit with license problem anyway, because you project will cause the inclusion of GPL and AGPL libraries. So it won't be affected directly, but indirectly.

**Comment by StevenTCramer** [comment]
I think solution to this probably would be to pull out the cloning to its own library/ repo?

**Comment by astrowalker** [comment]
It would be solution for sure, but since they are already clone projects with relaxed license, I would use them. No point reinventing the wheel.

**Comment by StevenTCramer** [comment]
Any clone has changed it license so no longer an issue ;)
