### ISSUE TITLE
Fallback code for server-side mode would be appreciated

### ISSUE THREAD

**Issue by michaelvolz** [TimeWarpEngineering/blazor-state#30]
Hi, I am using Blazor.State for a while now and I like it very much. I am used to MediatR, that made it a simple choice for me.

The new ASP.NET CORE roadmap shows, that Blazor server-side will be released first (called Razor-Components). It would be incredible valuable, If we could use Blazor.State for both modes.

Request: The store should be **unique to the current user-session**. Maybe even optional, to have a global-state (Themes, Locale ...) for everyone and personal state for the rest.

Do you think this is feasable?

Memory management could be something to think about too. Maybe saving state to disc or to Redis or SQL would give additional value.

**Comment by michaelvolz** [comment]
@StevenTCramer 

- Is this something you would consider? 
- Or should I do this on my own? 
- Do you want to continue this project? 
- Would you accept pull requests? 
- Would you accept a discussion about this issue?

**I am fine with everything. I just want to make some decisions.** 

I looked at the other state management libraries for Blazor and still find Blazor-State best suited for me as a long time C# developer.

Best regards.

**Comment by StevenTCramer** [comment]
@michaelvolz  Actually I have Blazor-State working Server side now and hope to push that out this weekend.  I also have DualMode that will use localstorage to write a flag.  On first visit to site it will open serverside and then open the clientside version in a hidden IFrame to cache the site locally.  Next time you visit the site it will detect and run it clientside.

**Comment by Sire** [comment]
@michaelvolz is this commited? I couldn't find anything in the documentation about Razor Components (server side Blazor).

**Comment by michaelvolz** [comment]
I am pausing at the moment to see where the Blazor/Razor code is heading. So I am not up to date.

**Comment by Sire** [comment]
> Actually I have Blazor-State working Server side now and hope to push that out this weekend. 

@michaelvolz is this commited? Thanks!

**Comment by StevenTCramer** [comment]
It works for 0.8.0.

**Comment by StevenTCramer** [comment]
0.9.0 broke some things

**Comment by StevenTCramer** [comment]
@michaelvolz  @Sire you can see running demo at https://blazor-state.azurewebsites.net/ using 0.8.0

I am going to wait till the next version of Blazor (1.0.0.preview) I think in next couple of weeks.  To see if they better support switching from server to client.
