### ISSUE TITLE
What is the reasoning behind the NonNestedClassException?

### ISSUE THREAD

**Issue by DerekChasse** [TimeWarpEngineering/blazor-state#306]
I'm wondering what the reasoning is behind this nested class convention?

I have a 'clean-architecture' setup in my application with a core project which defines Mediatr requests/notification/handlers etc...  I have my own conventions applied.  I'd love to use this project to also manage state across the different components/pages, but I'm butting heads with this convention.  To make Blazor-State happy I need to wrap each Action and Handler with a unnecessary partial class definition and munge my namespaces to allow things to resolve.

https://github.com/TimeWarpEngineering/blazor-state/blob/70fea1e4bf3709a29492bad468e1d2f98bba80af/Source/BlazorState/Pipeline/RenderSubscriptions/RenderSubscriptionsPostProcessor.cs#L41

**Comment by StevenTCramer** [comment]
Derek,


[RenderSubscriptionsPostProcessor.cs](https://github.com/TimeWarpEngineering/blazor-state/blob/70fea1e4bf3709a29492bad468e1d2f98bba80af/Source/BlazorState/Pipeline/RenderSubscriptions/RenderSubscriptionsPostProcessor.cs#L41) This particular middleware is used to enforce the constraint.  

And the `DeclaringType` is used by the [CloneStateBehavior](https://github.dev/TimeWarpEngineering/blazor-state/blob/02eba8edd442364af287689d7e519be609c15fff/Source/BlazorState/Pipeline/CloneState/CloneStateBehavior.cs#L56)middleware to determine what State needs to be cloned.

> I have a 'clean-architecture' setup in my application with a core project which defines Mediatr requests/notification/handlers etc...

Do you mean in your API code?
I am not clear why this causes you an issue when managing the state used in the browser(client).  
To give me a bit more context, are you doing Server Side Blazor or WASM?  Are you using the "hosted" template/pattern?

If you have an example that you can share would also help.

Thanks

Feel free to reach out to me on discord. https://discord.gg/jY4TNPEuCX
