### ISSUE TITLE
Question about setting state from outside state class

### ISSUE THREAD

**Issue by david-randoll** [TimeWarpEngineering/blazor-state#307]
Hello,

Since property in a state has a private set, if an action is in a separate class than the state's class how would I update the state? I was following the counter tutorial and see there is a Store.SetState but unsure how to update the state.

In the Handle method below, what do I include in the SetState method?

```C#
public partial class CounterState : State<CounterState>
{
    public int Count { get; private set; }
    public override void Initialize()
    {
        Count = 3;
    }
}
```

```C#
public class IncrementCount
{
    public class Action : IAction
    {
        public int Amount { get; set; }
    }

    public class Handler : ActionHandler<Action>
    {
        public Handler(IStore aStore) : base(aStore) { }
        CounterState _counterState => Store.GetState<CounterState>();

        public override Task<Unit> Handle(Action aAction, CancellationToken aCancellationToken)
        {
            int counter = _counterState.Count + aAction.Amount;
            Store.SetState();
            return Unit.Task;
        }
    }
}
```

Thank you!

**Comment by StevenTCramer** [comment]
Hi @david-randoll 

The flux pattern is designed to eliminate changes in state by anything other than handlers/reducers.  And those handlers are initiated by Actions only. The specific State is encapsulated.  All properties should be read-only outside the class.  The handlers should be child/nested classes of the state they mutate (this gives the handler access to private setters and thus it can mutate the values) 

In the CounterState example the Handler should be a nested class of CounterState.

https://timewarpengineering.github.io/blazor-state/Tutorial.html#handling-the-action

```csharp
public partial class CounterState // <== this makes it nested in CounterState
{
    public class IncrementCountHandler : ActionHandler<IncrementCountAction>
    {
        public IncrementCountHandler(IStore aStore) : base(aStore) { }

        CounterState CounterState => Store.GetState<CounterState>();

        public override Task<Unit> Handle(IncrementCountAction aIncrementCountAction, CancellationToken aCancellationToken)
        {
            CounterState.Count = CounterState.Count + aIncrementCountAction.Amount; // <== because nested it can access the setters.
            return Unit.Task;
        }
    }
}
```

Does this clear it up?

**Comment by david-randoll** [comment]
Yeah, I saw this in the tutorial but didn't like everything being within the state class as this class will become big really quick. If I were to move the IncrementCountHandler class to its own file there's no way to update the counter variable? Thru constructor?

**Comment by StevenTCramer** [comment]
@david-randoll  Having By using partial classes, you can have them in the class and in different files. Which is how I do it in the [Sample](https://github.com/TimeWarpEngineering/blazor-state/blob/master/Samples/Tutorial/Sample/Client/Features/Counter/Actions/IncrementCount/IncrementCountHandler.cs) 

![image](https://user-images.githubusercontent.com/357219/177451484-815043d1-0a50-4f47-80b6-ba215ab2b98b.png)

Hope this helps.

**Comment by david-randoll** [comment]
Ohh that makes sense; I miss understood the tutorial when I went thru it. This is what I was looking for.
