### ISSUE TITLE
Combine Features and Pages

### ISSUE THREAD

**Issue by michaelvolz** [TimeWarpEngineering/blazor-state#31]
Hi, I suggest combining the `Features` and `Pages` folders. The `Counter.cshtml` (and in my case the additional `Counter.cshtml.cs`) files should be placed beside the other code.

The whole concept of feature folders was to have exactly ONE place to look for one feature. Even `CSS/SCSS` and `JS` should be placed here IMHO.

You can just rename `Pages` to `Features`. `Blazor `will find the pages.

I would even move `NavMenu` and `SurveyPrompt` into the `Features ` folder.  They are components too.
The only exception has to be the `MainLayout.cshtml`, it seems to be a `Blazor` restriciton.

[Feature Folder Structure in ASP.NET Core](https://scottsauber.com/2016/04/25/feature-folder-structure-in-asp-net-core/)

**Comment by StevenTCramer** [comment]
@michaelvolz As I am using Blazor more and more on some real projects I am vetting out the folder structure.  You will see some changes soon.

Feature are currently organized by State.  
Components are reusable that don't depend on state.
I am changing Shared to Layout.  And I move SurveyPrompt to Components.
I am basing much of this off of lessons learned in my React apps.

I would love your feedback after I push out the updates to the the new timewarp-blazor template.

Thanks!

**Comment by StevenTCramer** [comment]
This issue is more related to the now separated timewarp-templates repository.
https://github.com/TimeWarpEngineering/timewarp-templates
