### ISSUE TITLE
State should not be shared by duplicate components as an option

### ISSUE THREAD

**Issue by michaelvolz** [TimeWarpEngineering/blazor-state#32]
Take the Counter component. Say you put 3 versions on the same page.  If you click the button multiple times, the state changes in one component. If you navigate away and back, all three components now show the same state. 

It would be useful to use the same component in an application without sharing state.

Or do you recommend another approach for this use case?

**Comment by StevenTCramer** [comment]
The subscriptions all work now so all components will be updated if based on the same state.  If you would want a component to connect to a different state then one would have to design state accordingly.
