### ISSUE TITLE
'Unable to load one or more of the requested types. Method 'Handle'  dependents on MediatR v12.0

### ISSUE THREAD

**Issue by neozhu** [TimeWarpEngineering/blazor-state#326]
please take a look at it.
when I update MediatR to v12.0  throw error
![image](https://user-images.githubusercontent.com/1549611/218913884-189ef2f7-af8a-4b76-927a-e6216a529064.png)

![image](https://user-images.githubusercontent.com/1549611/218914948-04a787aa-1d5a-45ba-817d-4f6793b3a624.png)

![image](https://user-images.githubusercontent.com/1549611/218915074-f6672558-e078-4724-9782-8202b3f08806.png)

**Comment by StevenTCramer** [comment]
Yes, Jimmy just released it last night while I was sleeping.  And there are breaking changes. Quite a few significant updates.
I probably won't get to this until Friday at earliest.

**Comment by neozhu** [comment]
I would like to participate in the collaboration of this project to complete the support for MediatR v12.0. However, I cannot compile the project that I cloned from GitHub on my local machine. Can you help me take a look?

![image](https://user-images.githubusercontent.com/1549611/219296363-d256b54e-f756-4d0c-9647-1528dd3394ae.png)

**Comment by StevenTCramer** [comment]
@neozhu I have started the update process and will continue in the morning.  Hopefully have version out tomorrow.

**Comment by StevenTCramer** [comment]
@neozhu I just pushed an update #329 so 8.0.0 is out.  Please let me know if you have any problems with it.  The Migration is NOT trivial this time. But Jimmy details the steps pretty well and I reference his notes in the mrigration docs.
