### ISSUE TITLE
Upgrading to 8.0.0 breaks viewer components updating

### ISSUE THREAD

**Issue by chris5287** [TimeWarpEngineering/blazor-state#332]
It appears the logic for the re-rending of components that listen to state being changed by another component has broken.

Repro before upgrading:
https://github.com/chris5287/blazor-state-repo/tree/Before-Working
![image](https://user-images.githubusercontent.com/1552744/223867872-fe058bb9-fd9e-405a-aada-bebe50bf1d7a.png)

Repro after upgrading:
https://github.com/chris5287/blazor-state-repo/tree/After-Broken
![image](https://user-images.githubusercontent.com/1552744/223867734-0e944769-e4a1-4ffe-b5be-7ab03afb810a.png)

**Comment by americanslon** [comment]
+1

**Comment by StevenTCramer** [comment]
We are aware and working on it.  It works server side but not in wasm.  We are trying to determine root cause.  Please join our discord server to follow the conversation.  Thanks :)
