### ISSUE TITLE
Failed to fetch dynamically imported module blazor-state.lib.module.js after changing app path

### ISSUE THREAD

**Issue by xtorcz** [TimeWarpEngineering/blazor-state#337]
I created a new blazor webassembly application and modified it as follows:

in index.html I edited 
```
<base href="/app/" />
<script src="/app/_framework/blazor.webassembly.js"></script>
```

modified property in the blazor client project
`<StaticWebAssetBasePath>app</StaticWebAssetBasePath>`

and modified the server project as follows:

```
   app.MapWhen(ctx => ctx.Request.Path.StartsWithSegments("/app"), first =>
            {
                first.UseBlazorFrameworkFiles("/app");
                first.UseStaticFiles();

                first.UseRouting();
                first.UseEndpoints(endpoints =>
                {
                    endpoints.MapControllers();
                    endpoints.MapFallbackToFile("app/{*path:nonfile}", "app/index.html");


                });
            });

```

after these modifications applications runs correctly on https://localhost:7231/app 

but only until I install the blazor-state package. Then you can see that the application is trying to load blazor-state.lib.module.js.
But this module and maybe others are generated in the default location.
https://localhost:7231/_content/Blazor-State/js/blazor-state.lib.module.js and application is trying loaded it from ..app path

Is there any way to fix this, or disable the use of blazor-state embedded resources and include the necessary JS manually?

Thanks
Tom

**Comment by StevenTCramer** [comment]
Hmm I would think it would work.

I have not tested this... but my first thought is to pass in options to the `UseStaticFiles();`  to map the /_content to /app/_content.

But the base path effects relative paths, so I don't know why it doesn't work. Slammed at the moment so will probably be next weekend unless someone else steps up :)

**Comment by mikeyoshino** [comment]
Hi, maybe it is a bit but you can put 
```app.UseStaticFiles("/app");``` along with your prefix and it will fix with location problem with any third library. :)

**Comment by StevenTCramer** [comment]
@mikeyoshino  Thanks for figuring this out.
@xtorcz  I'm going to close please let us know if any other issues.
