### ISSUE TITLE
Question - Getting Values At Start Up

### ISSUE THREAD

**Issue by nhwilly** [TimeWarpEngineering/blazor-state#348]
I need to initialize some items from storage when the app launches.  I'm using Blazored.

For now, I added some code to `App.razor=>OnInitializedAsync()` to fetch them from local storage and then send them through mediator to an `State<ApplicationState> object using a `SetValuesFromStorage` action to prevent cascading events.

But I thought it might also be possible to introduce that read into the initialize method of the state object.  Blazored has a sync method of the local storage service.

I know the `State` object is initialized before the `OnInitializedAsync` method runs.

Is one approach better than the other?

**Comment by StevenTCramer** [comment]
I like to have all interactions with the UI go through the blazor-state pipeline.   Which is the way you are currently doing it.  Eventhough you example is using LocalStorage it could just as easily be fetching from something external.

The State.Initialize should NOT interact with anything external or it will bypass the pipeline.

Your current method is the recommended method.
