### ISSUE TITLE
Error during Azure pipelines publish

### ISSUE THREAD

**Issue by americanslon** [TimeWarpEngineering/blazor-state#350]
This is a fun one. 
I am getting the following errors but ONLY when the publish is being done by an Azure pipeline. Local build works fine, local publish works fine.

`D:\a\1\s\TPL\Client\Core\States\Breadcrumbs\Actions\SetCrumbsAction.cs(8,22): error BlazorStateAction: The Action 'SetCrumbsAction' is not a nested type of its State [D:\a\1\s\TPL\Client\TPL.Client.csproj]
D:\a\1\s\TPL\Client\Core\States\ContextualFAB\Actions\SetButtonsAction.cs(8,22): error BlazorStateAction: The Action 'SetButtonsAction' is not a nested type of its State [D:\a\1\s\TPL\Client\TPL.Client.csproj]
D:\a\1\s\TPL\Client\Core\States\DisplaySize\Actions\SetBreakpointAction.cs(8,22): error BlazorStateAction: The Action 'SetBreakpointAction' is not a nested type of its State [D:\a\1\s\TPL\Client\TPL.Client.csproj]
D:\a\1\s\TPL\Client\Core\States\DisplaySize\Actions\SetHeightWidthAction.cs(7,22): error BlazorStateAction: The Action 'SetHeightWidthAction' is not a nested type of its State [D:\a\1\s\TPL\Client\TPL.Client.csproj]
D:\a\1\s\TPL\Client\Core\States\HttpInProgress\Actions\SetInProgressAction.cs(7,22): error BlazorStateAction: The Action 'SetInProgressAction' is not a nested type of its State [D:\a\1\s\TPL\Client\TPL.Client.csproj]`

Started with 8.2.0 (maybe 8.2.1). The same code has been running just fine for about six months.
Reverting back to 8.1.0 fixes the issue.
Let me know if I can provide any more details.

**Comment by StevenTCramer** [comment]
8.2.2 is out could you please try that and report back.  Thank you and I'm sorry for the error.  I have learned a lot about analyzers and still much to learn.

**Comment by americanslon** [comment]
Both 8.2.2 and 8.2.3 are still resulting in the same errors :(

No problem, these things happen.
What's an analyzer in this context and how come it only breaks in Azure pipeline and not locally?

**Comment by StevenTCramer** [comment]
Dang thing is confusing.  They are really hard to debug and caching happens all over the place.  I will try again later today.  Thanks much for your feedback.

I will get there eventually.

**Comment by StevenTCramer** [comment]
@americanslon please try 8.2.4

**Comment by americanslon** [comment]
@StevenTCramer Just wanted to let you know I can't try this for a couple of days but I remember it and will try it.

**Comment by americanslon** [comment]
8.2.4 seems to be working for me.
